export enum DishType {
  BiscuitsAndCookies = 'Biscuits and cookies',
  Bread = 'Bread',
  Cereals = 'Cereals',
  CondimentsAndSauces = 'Condiments and sauces',
  Desserts = 'Desserts',
  Drinks = 'Drinks',
  MainCourse = 'Main course',
  Pancake = 'Pancake',
  Preps = 'Preps',
  Preserves = 'Preserve',
  Salad = 'Salad',
  Sandwiches = 'Sandwiches',
  SideDish = 'Side dish',
  Soup = 'Soup',
  Starter = 'Starter',
  Sweets = 'Sweets',
}
